const Map<String, String> en = {
  // App specific
  'app_name': 'Ciber Paz Guardian Kids',
  'hello_world': 'Hello World!',
  'start': 'Start',
  'start_button_pressed': 'Start button pressed!',
  
  // Language
  'language': 'Language',
  'english': 'English',
  'spanish': 'Spanish',
  
  // Home
  'child_module': 'Child Module',
  'parent_module': 'Parent Module',
  'select_module': 'Select a Module',
  'app_subtitle': 'Proposed Solution - Ciber Paz Demo',
  'app_description': 'A chat simulator to train children on identifying and avoiding online dangers like grooming, sexting, and cyberbullying through interactive scenarios.',
  'demo_version': 'Demo Version - Hackathon 2025',
  'start_learning': 'Start Learning',
  'try_child_module': 'Try Child Module',
  'our_solution': 'Our Solution',
  
  // Chat
  'chat_title': 'Chat',
  'type_message': 'Type a message...',
  'send': 'Send',
  'loading': 'Loading...',
  'error_api': 'Error connecting to API',
  'chat_started': 'Chat started. Be careful!',
  'game_over': 'Game Over!',
  'you_lost': 'You Lost!',
  'play_again': 'Play Again',
  'go_back': 'Go Back',
  'online': 'online',
  'you_won': 'You Won!',
  'you_won_message': 'Great! You didn\'t fall into the trap!',
  'safety_tip': 'Safety Tip',
  'points_earned': 'Points earned',
  
  // Profile
  'profile': 'Profile',
  'points': 'Points',
  'games_won': 'Games Won',
  'games_lost': 'Games Lost',
  'total_games': 'Total Games',
  'enter_simulator': 'Enter Simulator',
  'your_stats': 'Your Stats',
  
  // Info Screen
  'about_title': 'About ecoGuardians',
  'about_subtitle': 'Cybersecurity education through gamification',
  'child_module_title': 'Child Module: Interactive Simulator',
  'child_module_desc': 'The Simulator is an educational game where children face realistic online danger scenarios through an AI-powered interactive chat.',
  'how_it_works': 'How does it work?',
  'how_it_works_1': 'Children enter a chat with a "stranger" (AI)',
  'how_it_works_2': 'The AI acts as a stranger trying to obtain personal information, photos, or create risky situations',
  'how_it_works_3': 'The child must identify warning signs and protect their information',
  'how_it_works_4': 'If they share private data: LOSES and receives an educational explanation',
  'how_it_works_5': 'If they complete 20 messages without falling: WINS and receives points + safety tips',
  'educational_scenarios': 'Educational scenarios:',
  'scenario_grooming': '🎮 Grooming: Manipulation to obtain external contact',
  'scenario_sexting': '💕 Sexting: Emotional pressure to send photos',
  'scenario_cyberbullying': '😡 Cyberbullying: Intimidation and emotional blackmail',
  'unique_experience': 'Each game is unique thanks to AI, which adapts its strategies and personality to create varied and realistic learning experiences.',
  'parent_module_title': 'Parent Module: Smart Monitoring',
  'parent_module_desc': 'Parents have access to a control panel that allows them to understand their children\'s digital behavior without invading their privacy.',
  'functionalities': 'Features:',
  'func_screen_time': '📊 Screen time per app (TikTok, Instagram, WhatsApp, etc.)',
  'func_periods': '📅 Analysis by periods: Today, This week, This month',
  'func_alerts': '🚨 AI-detected security alerts',
  'func_patterns': '⚠️ Suspicious patterns in conversations',
  'func_night': '🌙 Excessive nighttime usage detection',
  'alerts_desc': 'Alerts are classified by severity (High, Medium, Low) and provide context so parents can make informed decisions and open constructive conversations with their children.',
  'how_solves': 'How does it solve the problem?',
  'how_solves_desc': 'ecoGuardians addresses digital risk prevention from two complementary fronts:',
  'education_for_kids': '1. Experiential education for children',
  'edu_active': 'Active learning: Children experience real situations in a safe environment',
  'edu_no_consequences': 'No real consequences: They can make mistakes and learn from them',
  'edu_feedback': 'Immediate feedback: Educational explanations when they lose',
  'edu_gamification': 'Gamification: Points and achievements maintain interest',
  'empowerment_parents': '2. Empowerment for parents',
  'emp_visibility': 'Visibility without invasion: Aggregated data that respects privacy',
  'emp_detection': 'Early detection: Alerts before serious incidents occur',
  'emp_dialogue': 'Basis for dialogue: Information for constructive conversations',
  'education_promotion': 'Promoting education',
  'education_promotion_desc': 'Our platform goes beyond simple protection, creating a culture of cybersecurity:',
  'promo_critical': '🎯 Critical thinking: Children learn to analyze suspicious conversations',
  'promo_protection': '🛡️ Self-protection: They develop instincts to identify dangers',
  'promo_resilience': '💪 Digital resilience: They know how to react to risky situations',
  'promo_communication': '👨‍👩‍👧 Family communication: Facilitates conversations about digital safety',
  'promo_continuous': '📚 Continuous education: Each game reinforces security concepts',
  'final_message': 'By combining AI technology, gamification, and smart monitoring, ecoGuardians transforms cybersecurity education from something abstract and boring into a practical, entertaining, and memorable experience.',
  'our_mission': 'Our mission',
  'mission_text': 'Create a safer digital environment for the next generation, equipping children and parents with the necessary tools to navigate the digital world with confidence.',
};
