const Map<String, String> es = {
  // App specific
  'app_name': 'Ciber Paz Guardian Kids',
  'hello_world': '¡Hola Mundo!',
  'start': 'Iniciar',
  'start_button_pressed': '¡Botón de inicio presionado!',
  
  // Language
  'language': 'Idioma',
  'english': 'Inglés',
  'spanish': 'Español',
  
  // Home
  'child_module': 'Módulo Hijo',
  'parent_module': 'Módulo Padre',
  'select_module': 'Selecciona un Módulo',
  'app_subtitle': 'Solución Propuesta - Ciber Paz Demo',
  'app_description': 'Un simulador de chats para entrenar a los niños en identificar y evitar peligros en línea como grooming, sexting y ciberacoso a través de escenarios interactivos.',
  'demo_version': 'Versión Demo - Hackathon 2025',
  'start_learning': 'Comenzar a Aprender',
  'try_child_module': 'Probar Módulo Hijo',
  'our_solution': 'Nuestra Solución',
  
  // Chat
  'chat_title': 'Chat',
  'type_message': 'Escribe un mensaje...',
  'send': 'Enviar',
  'loading': 'Cargando...',
  'error_api': 'Error al conectar con la API',
  'chat_started': 'Chat iniciado. ¡Ten cuidado!',
  'game_over': '¡Juego Terminado!',
  'you_lost': '¡Perdiste!',
  'play_again': 'Jugar de Nuevo',
  'go_back': 'Volver',
  'online': 'en línea',
  'you_won': '¡Ganaste!',
  'you_won_message': '¡Excelente! No caíste en la trampa!',
  'safety_tip': 'Consejo de Seguridad',
  'points_earned': 'Puntos ganados',
  
  // Profile
  'profile': 'Perfil',
  'points': 'Puntos',
  'games_won': 'Juegos Ganados',
  'games_lost': 'Juegos Perdidos',
  'total_games': 'Juegos Totales',
  'enter_simulator': 'Entrar al Simulador',
  'your_stats': 'Tus Estadísticas',
  
  // Info Screen
  'about_title': 'Sobre ecoGuardians',
  'about_subtitle': 'Educación en ciberseguridad a través de la gamificación',
  'child_module_title': 'Módulo Hijo: Simulador Interactivo',
  'child_module_desc': 'El Simulador es un juego educativo donde los niños enfrentan escenarios realistas de peligros en línea mediante un chat interactivo impulsado por Inteligencia Artificial.',
  'how_it_works': '¿Cómo funciona?',
  'how_it_works_1': 'Los niños ingresan a un chat con un "desconocido" (IA)',
  'how_it_works_2': 'La IA actúa como un extraño que intenta obtener información personal, fotos o generar situaciones de riesgo',
  'how_it_works_3': 'El niño debe identificar señales de alerta y proteger su información',
  'how_it_works_4': 'Si comparte datos privados: PIERDE y recibe una explicación educativa',
  'how_it_works_5': 'Si completa 20 mensajes sin caer: GANA y recibe puntos + consejos de seguridad',
  'educational_scenarios': 'Escenarios educativos:',
  'scenario_grooming': '🎮 Grooming: Manipulación para obtener contacto externo',
  'scenario_sexting': '💕 Sexting: Presión emocional para enviar fotos',
  'scenario_cyberbullying': '😡 Cyberbullying: Intimidación y chantaje emocional',
  'unique_experience': 'Cada partida es única gracias a la IA, que adapta sus estrategias y personalidad para crear experiencias de aprendizaje variadas y realistas.',
  'parent_module_title': 'Módulo Padre: Monitoreo Inteligente',
  'parent_module_desc': 'Los padres tienen acceso a un panel de control que les permite comprender el comportamiento digital de sus hijos sin invadir su privacidad.',
  'functionalities': 'Funcionalidades:',
  'func_screen_time': '📊 Tiempo de pantalla por aplicación (TikTok, Instagram, WhatsApp, etc.)',
  'func_periods': '📅 Análisis por períodos: Hoy, Esta semana, Este mes',
  'func_alerts': '🚨 Alertas de seguridad detectadas por IA',
  'func_patterns': '⚠️ Patrones sospechosos en conversaciones',
  'func_night': '🌙 Detección de uso nocturno excesivo',
  'alerts_desc': 'Las alertas están clasificadas por severidad (Alta, Media, Baja) y proporcionan contexto para que los padres puedan tomar decisiones informadas y abrir conversaciones constructivas con sus hijos.',
  'how_solves': '¿Cómo resuelve el problema?',
  'how_solves_desc': 'ecoGuardians aborda la prevención de riesgos digitales desde dos frentes complementarios:',
  'education_for_kids': '1. Educación experiencial para niños',
  'edu_active': 'Aprendizaje activo: Los niños experimentan situaciones reales en un entorno seguro',
  'edu_no_consequences': 'Sin consecuencias reales: Pueden cometer errores y aprender de ellos',
  'edu_feedback': 'Retroalimentación inmediata: Explicaciones educativas cuando pierden',
  'edu_gamification': 'Gamificación: Puntos y logros mantienen el interés',
  'empowerment_parents': '2. Empoderamiento para padres',
  'emp_visibility': 'Visibilidad sin invasión: Datos agregados que respetan la privacidad',
  'emp_detection': 'Detección temprana: Alertas antes de que ocurran incidentes graves',
  'emp_dialogue': 'Base para el diálogo: Información para conversaciones constructivas',
  'education_promotion': 'Fomento de la educación',
  'education_promotion_desc': 'Nuestra plataforma va más allá de la simple protección, creando una cultura de ciberseguridad:',
  'promo_critical': '🎯 Pensamiento crítico: Los niños aprenden a analizar conversaciones sospechosas',
  'promo_protection': '🛡️ Autoprotección: Desarrollan instintos para identificar peligros',
  'promo_resilience': '💪 Resiliencia digital: Saben cómo reaccionar ante situaciones de riesgo',
  'promo_communication': '👨‍👩‍👧 Comunicación familiar: Facilita conversaciones sobre seguridad digital',
  'promo_continuous': '📚 Educación continua: Cada juego refuerza conceptos de seguridad',
  'final_message': 'Al combinar tecnología de IA, gamificación y monitoreo inteligente, ecoGuardians transforma la educación en ciberseguridad de algo abstracto y aburrido a una experiencia práctica, entretenida y memorable.',
  'our_mission': 'Nuestra misión',
  'mission_text': 'Crear un entorno digital más seguro para la próxima generación, equipando a niños y padres con las herramientas necesarias para navegar el mundo digital con confianza.',
};
